name: General Knowledge

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 08:00 UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Make sure you have a requirements.txt file
          # Or, if you don't have requirements.txt:
          # pip install python-dotenv google-api-python-client requests

      - name: Run Python script
        run: python main.py
        env:
          # Pass GitHub Secrets as environment variables to the script
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
